backend:
  name: github
  repo: pdlozano/main
  branch: blog  # Do not automatically publish it to main site
  base_url: "https://davidlozano.me"
  auth_endpoint: "api/auth"
media_folder: public/img
public_folder: img
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "DD MMM YYYY"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "portfolio"
    label: "Portfolio Items"
    folder: "portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "DD MMM YYYY"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Body"
        name: "body"
        widget: "markdown"